In [3]:
import numpy as np
# Get a reference to the policy
from ray.rllib.agents.ppo import PPOTrainer
trainer = PPOTrainer(env="CartPole-v0", config={"framework": "tf2", "num_workers": 0})
policy = trainer.get_policy()

In [5]:
# Run a forward pass to get model output logits. Note that complex observations
# must be preprocessed as in the above code block.
logits, _ = policy.model({"obs": np.array([[0.1, 0.2, 0.3, 0.4]])})

In [7]:
policy.dist_class

ray.rllib.models.tf.tf_action_dist.Categorical

In [8]:
dist = policy.dist_class(logits, policy.model)

In [9]:
dist.sample()

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>

In [10]:
dist.logp([1])

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.6932145], dtype=float32)>

In [11]:
policy.model.value_function()

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.00657655], dtype=float32)>

In [12]:
policy.model.base_model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 observations (InputLayer)      [(None, 4)]          0           []                               
                                                                                                  
 fc_1 (Dense)                   (None, 256)          1280        ['observations[0][0]']           
                                                                                                  
 fc_value_1 (Dense)             (None, 256)          1280        ['observations[0][0]']           
                                                                                                  
 fc_2 (Dense)                   (None, 256)          65792       ['fc_1[0][0]']                   
                                                                                            